stages:
  - build

variables:
  IMAGE_NAME: "laravel-docker"
  GITLAB_IMAGE: "$CI_REGISTRY_IMAGE/$IMAGE_NAME"
  DOCKERHUB_IMAGE: "$DOCKERHUB_USERNAME/$IMAGE_NAME"

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    #- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  script:
    - >
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        for version in 8.0 8.1 8.2 8.3; do
          docker build -t $GITLAB_IMAGE:$version -f $version/Dockerfile .
          docker push $GITLAB_IMAGE:$version
        done
      fi
