stages:
  - build
  - publish

variables:
  IMAGE_NAME: "laravel-docker"
  GITLAB_IMAGE: "$CI_REGISTRY_IMAGE/$IMAGE_NAME"
  DOCKERHUB_IMAGE: "$DOCKERHUB_USERNAME/$IMAGE_NAME"

.docker_template: &docker_template
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --update --no-cache git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_PHP_8_0_image:
  <<: *docker_template
  stage: build
  script:
    - docker build -t $GITLAB_IMAGE:8.0 -f 8.0/Dockerfile .

publish_PHP_8_0_image:
  <<: *docker_template
  stage: publish
  script:
    - docker build -t $GITLAB_IMAGE:8.0 -f 8.0/Dockerfile .
    - docker push $GITLAB_IMAGE:8.0
  only:
    - main

build_PHP_8_1_image:
  <<: *docker_template
  stage: build
  script:
    - docker build -t $GITLAB_IMAGE:8.1 -f 8.1/Dockerfile .

publish_PHP_8_1_image:
  <<: *docker_template
  stage: publish
  script:
    - docker build -t $GITLAB_IMAGE:8.1 -f 8.1/Dockerfile .
    - docker push $GITLAB_IMAGE:8.1
  only:
    - main

build_PHP_8_2_image:
  <<: *docker_template
  stage: build
  script:
    - docker build -t $GITLAB_IMAGE:8.2 -f 8.2/Dockerfile .

publish_PHP_8_2_image:
  <<: *docker_template
  stage: publish
  script:
    - docker build -t $GITLAB_IMAGE:8.2 -f 8.2/Dockerfile .
    - docker push $GITLAB_IMAGE:8.2
  only:
    - main

build_PHP_8_3_image:
  <<: *docker_template
  stage: build
  script:
    - docker build -t $GITLAB_IMAGE:8.3 -f 8.3/Dockerfile .

publish_PHP_8_3_image:
  <<: *docker_template
  stage: publish
  script:
    - docker build -t $GITLAB_IMAGE:8.3 -f 8.3/Dockerfile .
    - docker push $GITLAB_IMAGE:8.3
  only:
    - main